//
//  RickyNet-Bridging-Header.h
//  Exposes the rickynet-core C ABI (rn_start / rn_stop / rn_stats) to Swift.
//  rickynetcore.h is generated by cbindgen in CI into Vendor/include/.
//

#ifndef RICKYNET_BRIDGING_HEADER_H
#define RICKYNET_BRIDGING_HEADER_H

#include "rickynetcore.h"

#endif /* RICKYNET_BRIDGING_HEADER_H */
